Added a check to ensure that the shortest path is followed when inter…
UniversalRobots/Universal_Robots_ROS_controllers_cartesian pull request #14
Opened 2022-08-10 10:45 UTC by urmahp

…polating between two orientations

Changed the order of multiplication when calculating the quaternion based velocity and acceleration, since the velocity and acceleration is given in the body-local reference frame. 
The math supporting this change, can be found [here](https://arxiv.org/abs/0811.2889v1).

Added unit tests to verify the changes.

If the dot product between two orientations is negative, the sign is flipped on one of them to ensure that we take the shortest path. Without this we could end up interpolating between two identical orientations, but with opposite signs.

This should fix the [issue](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/540). 

To test the following motion will fail on the old version, but work with these changes.
start_pose.position = [-0.63316, -0.50412, 0.07724]
start_pose.orientation = [0.1046779, -0.7045626, 0.1234662, 0.6909343]

end_pose.position =  [-0.78590, -0.19334, 0.07724]
end_pose.orientation = [0.0485966, 0.7107247, 0.031284, -0.7010921]

2022-08-11 08:20 UTC, stefanscherzinger requested changes
Thanks @urmahp for this fix!

Your contribution is very welcome!
I would recommend, however, that we split this PR into two parts:
1) Your fix (see my small suggestions)
2) The changes of coordinates when handling *body-local* quaternion velocities and accelerations. While `2.` seems reasonable (thanks for the paper reference), I feel we need a separate integration test to cover this use case. I think we currently don't do much velocity or acceleration conditions in the waypoints. But that's exactly where these mechanism show themselves. If you agree, We could take the opportunity to clarify this aspect in a separate PR.

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/src/cartesian_trajectory.cpp
> +      state.q.w() = state.q.w() * -1;
```suggestion
      state.q = state.q.conjugate();
```

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/src/cartesian_trajectory.cpp
> +                         state.q.z() * next_state.q.z() + state.q.w() * next_state.q.w();
```suggestion
    double dot_product = state.q.dot(next_state.q);
```

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/src/cartesian_trajectory.cpp
> +      next_state.q.w() = next_state.q.w() * -1;
```suggestion
      next_state.q = next_state.q.conjugate();
```

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/test/cartesian_trajectory_test.cpp
> +  p2.pose.orientation.w = -0.0159721;
```suggestion
  p2.pose.orientation.x = - p1.pose.orientation.x;
  p2.pose.orientation.y = - p1.pose.orientation.y;
  p2.pose.orientation.z = - p1.pose.orientation.z;
  p2.pose.orientation.w = - p1.pose.orientation.w;
```

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/test/cartesian_trajectory_test.cpp
> +  p2.pose.orientation.w = -0.0159721;
I think that's cleaner and shows our intention at first sight.

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/src/cartesian_trajectory.cpp
> +      state.q.w() = state.q.w() * -1;
That won't negate the *real* part of the quaternion, but I think it's cleaner. Does that still work?

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/src/cartesian_trajectory.cpp
> +                         state.q.z() * next_state.q.z() + state.q.w() * next_state.q.w();
Less verbose and probably performance optimized. Do you want to keep the explicit computation for the sake of clarity?

2022-08-11 08:20 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/test/cartesian_trajectory_test.cpp
> +  // For the linear case, half the time should give half the values.
Does that comment fit to your test?

2022-08-11 08:54 UTC, urmahp commented
> Thanks @urmahp for this fix!
> 
> Your contribution is very welcome! I would recommend, however, that we split this PR into two parts:
> 
>     1. Your fix for the sign (see my small suggestions)
> 
>     2. The changes of coordinates when handling _body-local_ quaternion velocities and accelerations. While `2.` seems reasonable (thanks for the paper reference), I feel we need a separate integration test to cover this use case. I think we currently don't do much velocity or acceleration conditions in the waypoints. But that's exactly where these mechanism show themselves. If you agree, We could take the opportunity to clarify this aspect in a separate PR.

Thans for the feedback! 

I will split the PR into to two PR's and change the suggestions. 

I agree that using conjugate looks cleaner, when flipping the sign, however it wouldn't be correct since only flipping the sign on the complex part would result in a different orientation. You have to flip the sign of the whole quaternion in order to get the same orientation. We could use it to negate the complex part and then negate the real part afterwards.

2022-08-11 10:02 UTC, stefanscherzinger commented on cartesian_trajectory_interpolation/src/cartesian_trajectory.cpp
> +    // If the dot product is negative, we change the sing of the orientation to not travel the long way around
```suggestion
    // If the dot product is negative, we change the sign of the orientation to not travel the long way around
```

2022-08-11 11:14 UTC, stefanscherzinger approved these changes

2022-08-11 11:26 UTC, merged

2022-10-11 21:34 UTC, sebas775 commented
how this is integrated to the controller, can you share the steps please, I have an ur3e

2022-10-11 21:38 UTC, sebas775 reviewed
.